version: '3.8'
name: kgolapfrontend
volumes:
  data:
    driver: local
  cache:
    driver: local

services:
  cache:
    container_name: kgolap-redis
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data
    depends_on:
      - postgres

  postgres:
      container_name: kgolap-postgres
      image: postgres
      volumes:
        - data:/var/lib/postgresql/data
        - ./scripts:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_DB: kgolap
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - 5432:5432

  postgres-pgadmin4:
    container_name: kgolap-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres

  keycloak:
      container_name: kgolap-keycloak
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: kgolap
        DB_USER: ${POSTGRES_USER}
        DB_SCHEMA: keycloak
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      ports:
        - "8081:8080"
      depends_on:
        - postgres
      extra_hosts:
        - "host.docker.internal:host-gateway"

  app:
    container_name: kgolap-app
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
      - postgres
      - cache
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KEYCLOAK_ID: ${KEYCLOAK_ID}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_ISSUER: ${KEYCLOAK_URL}/auth/realms/kgolap
      KEYCLOAK_REFRESH_TOKEN_URL: ${KEYCLOAK_URL}/auth/realms/kgolap/protocol/openid-connect/token
      #KEYCLOAK_WELLKNOWN: http://kgolap-keycloak:8080/auth/realms/kgolap/.well-known/openid-configuration
      END_SESSION_URL: ${KEYCLOAK_URL}/auth/realms/kgolap/protocol/openid-connect/logout
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      KGOLAP_SURFACE_URL: ${KGOLAP_SURFACE_URL}
      KGOLAP_CUBE_URL: ${KGOLAP_CUBE_URL}
      KGOLAP_FILE_URL: ${KGOLAP_FILE_URL}
      KGOLAP_PREFIX_URL: ${KGOLAP_PREFIX_URL}
      KGOLAP_USERNAME: ${KGOLAP_USERNAME}
      KGOLAP_PASSWORD: ${KGOLAP_PASSWORD}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@kgolap-postgres:5432/kgolap?schema=kgolap"
      REDIS_URL: "redis://default:${REDIS_PASSWORD}@kgolap-redis:6379"
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}