version: '3.8'
name: kgolapfrontend
volumes:
  data:
      driver: local

services:
  postgres:
      container_name: postgres
      image: postgres
      volumes:
        - data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: 123
      ports:
        - 8081:8080
      depends_on:
        - postgres

