version: '3.8'
name: kgolapfrontend
volumes:
  data:
      driver: local
  cache:
    driver: local

services:
  cache:
    container_name: kgolap-redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redisPa55w0rd
    volumes: 
      - cache:/data
    depends_on:
      - postgres

  postgres:
      container_name: kgolap-postgres
      image: postgres
      volumes:
        - data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432

  postgres-pgadmin4:
    container_name: kgolap-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: k12345678@students.jku.at
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    depends_on:
      - postgres

  keycloak:
      container_name: kgolap-keycloak
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8081:8080
      depends_on:
        - postgres